version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - m2creates
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: markdown-it
    versions:
    - 12.0.4
    - 12.0.5
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
    - 7.0.2
